# Create Regression Models to Predict Income
## **A Notebook for Using Demographic Data to Predict Income/Wage**

In [2]:
import pandas as pd
import numpy as np

In [8]:
regression_df = pd.read_csv('preprocessed_data/regression_data.csv')
regression_df.drop(columns='Unnamed: 0', inplace=True)
regression_df

,AGEP,JWMNP,WAGP,WKHP,PINCP,DIVISION[East North Central],DIVISION[East South Central],DIVISION[Middle Atlantic],DIVISION[Mountain],DIVISION[New England],...,RAC1P[Other],RAC1P[WHT],WAOB[Africa],WAOB[Asia],WAOB[Europe],WAOB[Latin America],WAOB[Northern America],WAOB[Oceania and at Sea],WAOB[PR and US Island],WAOB[US State]
0,52,50.0,30000.0,40.0,30000.0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
1,49,20.0,109000.0,35.0,109000.0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,1
2,60,15.0,50000.0,40.0,50000.0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
3,37,0.0,0.0,0.0,0.0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
4,54,15.0,36100.0,40.0,36100.0,0,0,0,1,0,...,0,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305116,19,0.0,0.0,0.0,0.0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
305117,89,0.0,0.0,0.0,14000.0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
305118,58,60.0,100000.0,40.0,100000.0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
305119,26,7.0,13700.0,40.0,13700.0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
305120,68,0.0,0.0,0.0,10800.0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,0,1

In [51]:
def features_and_target(df):

    income = df['PINCP']
    regression_df.drop(labels=['PINCP'], axis=1, inplace = True)
    regression_df.insert(0, 'PINCP', income)

    target = regression_df["PINCP"]
    features = regression_df.iloc[0: , 1 : 101]
    return features, target

In [52]:
features, target = features_and_target(regression_df)

In [53]:
features

,AGEP,JWMNP,WAGP,WKHP,DIVISION[East North Central],DIVISION[East South Central],DIVISION[Middle Atlantic],DIVISION[Mountain],DIVISION[New England],DIVISION[Pacific],...,RAC1P[Other],RAC1P[WHT],WAOB[Africa],WAOB[Asia],WAOB[Europe],WAOB[Latin America],WAOB[Northern America],WAOB[Oceania and at Sea],WAOB[PR and US Island],WAOB[US State]
0,52,50.0,30000.0,40.0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,1
1,49,20.0,109000.0,35.0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,1
2,60,15.0,50000.0,40.0,0,0,0,0,0,1,...,0,1,0,0,0,0,0,0,0,1
3,37,0.0,0.0,0.0,0,0,0,0,0,1,...,0,1,0,0,0,1,0,0,0,0
4,54,15.0,36100.0,40.0,0,0,0,1,0,0,...,0,1,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305116,19,0.0,0.0,0.0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
305117,89,0.0,0.0,0.0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
305118,58,60.0,100000.0,40.0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
305119,26,7.0,13700.0,40.0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
305120,68,0.0,0.0,0.0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1

In [54]:
target

0          30000.0
1         109000.0
2          50000.0
3              0.0
4          36100.0
            ...
305116         0.0
305117     14000.0
305118    100000.0
305119     13700.0
305120     10800.0
Name: PINCP, Length: 305121, dtype: float64

OHHH okay I thought you were talking about two way categorical stuff... my bad Alex
U might wanna try out an 18-way ANOVA if u want, that could save time
Then you only have to go do 1-way ANOVAS on the catÃ©gories that weâ€™re significant from that 18-way test