# A Method to Extract 1% Samples of Data
## **Run only a, b, c, or d at a time to avoid memory overflow**

In [1]:
import pandas as pd

In [2]:
# psam_pusa = pd.read_csv('us_personal/psam_pusa.csv')
# psam_pusb = pd.read_csv('us_personal/psam_pusb.csv')
# psam_pusc = pd.read_csv('us_personal/psam_pusc.csv')
psam_pusd = pd.read_csv('us_personal/psam_pusd.csv')

In [3]:
# psam_pusa['WAGP'].describe()
# psam_pusb['WAGP'].describe()
# psam_pusc['WAGP'].describe()
psam_pusd['WAGP'].describe()

count    3.299316e+06
mean     2.800658e+04
std      5.027155e+04
min      0.000000e+00
25%      0.000000e+00
50%      8.000000e+03
75%      4.000000e+04
max      5.210000e+05
Name: WAGP, dtype: float64

In [8]:
# psam_pusa['RAC1P'].describe()
# psam_pusb['RAC1P'].describe()
# psam_pusc['RAC1P'].describe()
psam_pusd['RAC1P'].describe()

count    4.001965e+06
mean     1.699012e+00
std      1.898641e+00
min      1.000000e+00
25%      1.000000e+00
50%      1.000000e+00
75%      1.000000e+00
max      9.000000e+00
Name: RAC1P, dtype: float64

In [9]:
# psam_pusa_sample = psam_pusa.sample(frac=0.01)
# psam_pusa_sample
# psam_pusb_sample = psam_pusb.sample(frac=0.01)
# psam_pusb_sample
# psam_pusc_sample = psam_pusc.sample(frac=0.01)
# psam_pusc_sample
psam_pusd_sample = psam_pusd.sample(frac=0.01)
psam_pusd_sample

,RT,SERIALNO,DIVISION,SPORDER,PUMA,REGION,ST,ADJINC,PWGTP,AGEP,...,PWGTP71,PWGTP72,PWGTP73,PWGTP74,PWGTP75,PWGTP76,PWGTP77,PWGTP78,PWGTP79,PWGTP80
2432720,P,2018HU0373803,7,4,2302,3,48,1013097,24,9,...,25,21,6,46,9,28,45,38,43,8
3982306,P,2015000928439,8,1,200,4,56,1061242,3,65,...,3,3,2,4,4,1,1,1,3,2
2779978,P,2015000586572,1,2,100,1,50,1061242,5,67,...,5,6,5,5,1,1,5,5,2,5
1957524,P,2016000772825,7,5,1400,3,48,1054346,15,5,...,11,26,12,5,4,12,12,4,31,14
3921045,P,2018HU0129915,3,2,55103,2,55,1013097,9,16,...,3,14,2,2,10,11,14,13,3,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3506490,P,2017001338825,9,1,10504,4,53,1035838,26,71,...,7,23,25,28,26,27,43,27,6,8
1899062,P,2016000431856,7,1,3502,3,48,1054346,9,57,...,8,18,9,8,9,2,10,10,16,10
2353878,P,2018GQ0016638,7,1,3601,3,48,1013097,3,61,...,0,0,2,2,0,3,2,0,0,3
1062708,P,2015000410609,6,1,3202,3,47,1061242,24,38,...,40,44,7,25,21,38,7,23,21,40
3665977,P,2018HU0405036,5,4,400,3,54,1013097,33,20,...,37,19,29,36,12,37,35,37,14,25

In [10]:
# psam_pusa_sample.to_csv('us_personal/psam_pusa_sample.csv')
# psam_pusb_sample.to_csv('us_personal/psam_pusb_sample.csv')
# psam_pusc_sample.to_csv('us_personal/psam_pusc_sample.csv')
psam_pusd_sample.to_csv('us_personal/psam_pusd_sample.csv')

In [7]:
import pandas as pd

In [8]:
dfa = pd.read_csv('us_personal_sample/psam_pusa_sample.csv')
dfb = pd.read_csv('us_personal_sample/psam_pusb_sample.csv')
dfc = pd.read_csv('us_personal_sample/psam_pusc_sample.csv')
dfd = pd.read_csv('us_personal_sample/psam_pusd_sample.csv')

In [9]:
total = pd.concat([dfa, dfb, dfc, dfd])

In [10]:
total

,Unnamed: 0,RT,SERIALNO,DIVISION,SPORDER,PUMA,REGION,ST,ADJINC,PWGTP,...,PWGTP71,PWGTP72,PWGTP73,PWGTP74,PWGTP75,PWGTP76,PWGTP77,PWGTP78,PWGTP79,PWGTP80
0,3269865,P,2014000763571,5,1,3107,3,12,1070673,11,...,15,10,10,22,12,21,3,3,13,11
1,4124953,P,2018HU1163498,5,1,6300,3,12,1013097,13,...,4,23,28,4,13,14,5,12,3,24
2,1747317,P,2016000964524,9,2,5904,4,6,1054346,27,...,10,50,26,27,9,30,7,8,45,29
3,3025548,P,2017000168429,1,1,104,1,9,1035838,13,...,25,5,13,15,26,22,16,3,25,21
4,4303430,P,2015000747570,5,1,6002,3,13,1061242,19,...,14,15,27,23,7,18,34,4,20,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40015,3506490,P,2017001338825,9,1,10504,4,53,1035838,26,...,7,23,25,28,26,27,43,27,6,8
40016,1899062,P,2016000431856,7,1,3502,3,48,1054346,9,...,8,18,9,8,9,2,10,10,16,10
40017,2353878,P,2018GQ0016638,7,1,3601,3,48,1013097,3,...,0,0,2,2,0,3,2,0,0,3
40018,1062708,P,2015000410609,6,1,3202,3,47,1061242,24,...,40,44,7,25,21,38,7,23,21,40
40019,3665977,P,2018HU0405036,5,4,400,3,54,1013097,33,...,37,19,29,36,12,37,35,37,14,25